apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk3021-backend
  namespace: skala3-ai1
  labels:
    app: sk3021-backend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sk3021-backend
  template:
    metadata:
      labels:
        app: sk3021-backend
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: node-container
        # CD 파이프라인에서 이 부분을 동적으로 변경합니다.
        image: amdp-registry.skala-ai.com/skala26a-ai1/a3021_node:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        # 컨테이너의 /app/data 폴더와 PVC를 연결 (db.json과 이미지 저장 위치)
        volumeMounts:
        - name: data-storage
          mountPath: /app/data
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: sk3021-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sk3021-backend-svc
  namespace: skala3-ai1
spec:
  type: ClusterIP
  selector:
    app: sk3021-backend
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000